#include "zxgui.h"
#include "desktop.h"

static wchar_t tile_to_char_map[] = {
    L'╚' /* GUI_FORM_LEFT_BOTTOM_CORNER */,
    L'╝' /* GUI_FORM_RIGHT_BOTTOM_CORNER */,
    L'╗' /* GUI_FORM_RIGHT_TOP_CORNER */,
    L'╔' /* GUI_FORM_LEFT_TOP_CORNER */,
    L'═' /* GUI_FORM_TOP */,
    L'║' /* GUI_FORM_LEFT */,
    L'═' /* GUI_FORM_BOTTOM */,
    L'║' /* GUI_FORM_RIGHT */,
    L'└' /* GUI_EDIT_LEFT_BOTTOM_CORNER */,
    L'┘' /* GUI_EDIT_RIGHT_BOTTOM_CORNER */,
    L'┐' /* GUI_EDIT_RIGHT_TOP_CORNER */,
    L'┌' /* GUI_EDIT_LEFT_TOP_CORNER */,
    L'─' /* GUI_EDIT_TOP */,
    L'│' /* GUI_EDIT_LEFT */,
    L'─' /* GUI_EDIT_BOTTOM */,
    L'│' /* GUI_EDIT_RIGHT */,
    L'└' /* GUI_SELECT_LEFT_BOTTOM_CORNER */,
    L'┘' /* GUI_SELECT_RIGHT_BOTTOM_CORNER */,
    L'┐' /* GUI_SELECT_RIGHT_TOP_CORNER */,
    L'┌' /* GUI_SELECT_LEFT_TOP_CORNER */,
    L'─' /* GUI_SELECT_TOP */,
    L'│' /* GUI_SELECT_LEFT */,
    L'─' /* GUI_SELECT_BOTTOM */,
    L'│' /* GUI_SELECT_RIGHT */,
    L'█' /* GUI_EDIT_CURSOR */,
    L'↘' /* GUI_ICON_RETURN */,
    L'C' /* GUI_ICON_C */,
    L'■' /* GUI_ICON_LOADING_A_1 */,
    L'□' /* GUI_ICON_LOADING_A_2 */,
    L'□' /* GUI_ICON_LOADING_A_3 */,
    L'■' /* GUI_ICON_LOADING_A_4 */,
    L'▪' /* GUI_ICON_LOADING_B_1 */,
    L'▫' /* GUI_ICON_LOADING_B_2 */,
    L'▫' /* GUI_ICON_LOADING_B_3 */,
    L'▪' /* GUI_ICON_LOADING_B_4 */,
    L'━' /* GUI_ICON_SPACE */,
    L'⇩' /* GUI_ICON_MORE_TO_FOLLOW */,
    L'⇧' /* GUI_ICON_LESS_TO_FOLLOW */,
    L'P' /* GUI_ICON_P */,
    L'x' /* QUESTION_MARK_1 */,
    L'x' /* QUESTION_MARK_2 */,
    L'x' /* QUESTION_MARK_3 */,
    L'x' /* QUESTION_MARK_4 */,
    L'6' /* GUI_ICON_6 */,
    L'7' /* GUI_ICON_7 */,
    L'⇄' /* GUI_ICON_LOADING_SMALL_1 */,
    L'⇆' /* GUI_ICON_LOADING_SMALL_2 */,
    L'x' /* GUI_SELECTED_ENTRY */,
    L'◦' /* GUI_ICON_REPLIES */,
    L'»' /* GUI_ICON_REPLY */,
    L'H' /* GUI_ICON_H */,
    L'R' /* GUI_ICON_R */,
    L'N' /* GUI_ICON_N */,
    L'⌂' /* GUI_ICON_SYM */,
    L'5' /* GUI_ICON_5 */,
    L'T' /* GUI_ICON_T */,
    L'B' /* GUI_ICON_B */,
    L' ' /* GUI_ICON_EMPTY */,
    L'E' /* GUI_ICON_ESCAPE */,
};

wchar_t tile_to_char(enum gui_tiles t)
{
    return tile_to_char_map[t];
}
